server:
  port: 8601

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1