server:
  port: 8603

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

# 默认登录密码
DEFAULT_PASSWORD: 123456




