server:
  port: 8605
spring:
  application:
    name: ginkgo_search
#  jmx:
#    default-domain: mogu_search
  security:
    user:
      name: user
      password: password123
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300

#  boot:
#    admin:
#      client:
#        enabled: true
#        url: http://localhost:8606
#        username: user
#        password: password123
#      instance:
#        service-base-url: http://localhost:8605


eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5
