server:
  port: 8602

file:
  upload:
    path: D:/mogu_blog/data/

spring:
  application:
    name: ginkgo-picture
    security:
      user:
        name: user
        password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_picture?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root