server:
  port: 8604

#阿里大于
accessKeyId: XXXXXXXXXXXXXXXXXXXXX #修改成自己的
accessKeySecret: XXXXXXXXXXXXXXXXXXXXXXX #修改成自己的

spring:
  application:
    name: ginkgo-sms


  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: guest
    password: guest

  mail:
    username: mogublog@163.com
    password: a1313375 #授权码开启SMTP服务里设置
    host: smtp.163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false
