server:
  port: 8603

file:
  upload:
    path: D:/mogu_blog/data/

# 默认登录密码
DEFAULT_PASSWORD: 123456


spring:
  application:
    name: ginkgo-web
    security:
      user:
        name: user
        password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

