server:
  port: 8603

signName: 银杏博客
# 项目英文名
PROJECT_NAME_EN: ginkgoBlog
# 项目名称
PROJECT_NAME: 银杏博客

#博客相关配置
BLOG:
  HOT_COUNT: 5 #热门博客数量
  HOT_TAG_COUNT: 20 #热门标签数量
  FRIENDLY_LINK_COUNT: 20 #友情链接数
  NEW_COUNT: 15 #最新博客数据
  FIRST_COUNT: 5 #一级推荐
  SECOND_COUNT: 2 #二级推荐
  THIRD_COUNT: 3 #三级推荐
  FOURTH_COUNT: 5 #四级推荐
  USER_TOKEN_SURVIVAL_TIME: 168 # toekn令牌存活时间, 7天  168 = 7*24
  # 原创模板
  ORIGINAL_TEMPLATE: 本文为银杏博客原创文章，转载无需和我联系，但请注明来自银杏博客
  # 转载模板
  REPRINTED_TEMPLATE: 本着开源共享、共同学习的精神，本文转载自 %S ，版权归 %S 所有，如果侵权之处，请联系博主进行删除，谢谢~


data:
  # 门户页面
  webSite:
    url: http://localhost:9527/#/
  # mogu_web网址，用于第三方登录回调
  web:
    url: http://127.0.0.1:8603

file:
  upload:
    path: D:/mogu_blog/data/

# 默认登录密码
DEFAULT_PASSWORD: 123456



spring:
  application:
    name: ginkgo-web
    security:
      user:
        name: user
        password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  redis:
    host: 127.0.0.1 #redis的主机ip
    port: 6379

  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: guest
    password: guest

