server:
  port: 8603
#阿里大于
templateCode: SMS_XXXXXX #短信模板编号

signName: 银杏博客
# 项目英文名
PROJECT_NAME_EN: ginkgoBlog
# 项目名称
PROJECT_NAME: 银杏博客

data:
  # 门户页面
  webSite:
    url: http://localhost:9527/#/
  # mogu_web网址，用于第三方登录回调
  web:
    url: http://127.0.0.1:8603

file:
  upload:
    path: D:/mogu_blog/data/

# 默认登录密码
DEFAULE_PWD: 123456

#博客相关配置
BLOG:
  HOT_COUNT: 5 #热门博客数量
  HOT_TAG_COUNT: 20 #热门标签数量
  FRIENDLY_LINK_COUNT: 20 #友情链接数
  NEW_COUNT: 15 #最新博客数据
  FIRST_COUNT: 5 #一级推荐
  SECOND_COUNT: 2 #二级推荐
  THIRD_COUNT: 3 #三级推荐
  FOURTH_COUNT: 5 #四级推荐
  USER_TOKEN_SURVIVAL_TIME: 168 # toekn令牌存活时间, 7天  168 = 7*24
  # 原创模板
  ORIGINAL_TEMPLATE: 本文为银杏博客原创文章，转载无需和我联系，但请注明来自银杏博客
  # 转载模板
  REPRINTED_TEMPLATE: 本着开源共享、共同学习的精神，本文转载自 %S ，版权归 %S 所有，如果侵权之处，请联系博主进行删除，谢谢~


spring:
  application:
    name: ginkgo-web
  security:
    user:
      name: user
      password: password123
  datasource:
    url: jdbc:mysql://localhost:3306/ginkgo_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  redis:
    host: 127.0.0.1 #redis的主机ip
    port: 6379

  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: guest
    password: guest

  # jackson配置响应时间格式、时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai


#eureka相关配置
eureka:
  client:
#    healthcheck:
#      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5


# 第三方登录，参考 http://moguit.cn/#/info?blogUid=fe9e352eb95205a08288f21ec3cc69e0
justAuth:
  clientId:
    gitee: ec2dba332701caa209935512c69fc7962530b8619acd9b6cb03106a7c13c1c5e
    github: c99bfe31f8774ec8e242
    qq: XXXXXXXXXXXXXXX  # 改成自己的
  clientSecret:
    gitee: 993930de16b61b8146f7d30c693afd328b4d42116cf2da748f275077e4ef5e47
    github: ec088d14ab8076e2beed58fcb95e37a0fc586618
    qq: XXXXXXXXXXXXXXXXXX # 改成自己的