server:
  port: 8604

#阿里大于
accessKeyId: XXXXXXXXXXXXXXXXXXXXX #修改成自己的
accessKeySecret: XXXXXXXXXXXXXXXXXXXXXXX #修改成自己的

spring:
  application:
    name: ginkgo-sms
  security:
    user:
      name: user
      password: 123456

  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: guest
    password: guest

  mail:
    username: mogublog@163.com
    password: a1313375 #授权码开启SMTP服务里设置
    host: smtp.163.com
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false

eureka:
  client:
#    healthcheck:
#      enabled: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5